name: CI

on:
  push:

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "Only one at a time"
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #### Modify below here to match your project ####
        file:
          - test-stusb4500-esp32-s3-idf
          - test-tfmini-esp32-s3-idf
        #### Modify above here to match your project ####
        esphome-version:
          - stable
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Get latest ESPHome release tag
        id: esphome-release             # The step ID to refer to later
        uses: oprypin/find-latest-tag@v1
        with:
          repository: esphome/esphome   # The repository to scan
          releases-only: true           # We know that all relevant tags have a GitHub release for them

      - name: Get last tested ESPHome release tag
        id: test-release
        run: |
          tag=$(jq -r '.last_tested_tag' test/.test-data.json)

      - name: Update version
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          commitChange: false
          message: "Update version"
          branch: '${{ github.ref }}'
          changes: |
            {
              "test/test-stusb4500-esp32-s3-idf.yaml": {
                "external_components.source.re": "${{ github.ref }}"
              },
              "test/test-tfmini-esp32-s3-idf.yaml": {
                "external_components.source.re": "${{ github.ref }}"
              },
              "test/test-stusb4500-esp32-s3-ard.yaml": {
                "external_components.source.re": "${{ github.ref }}"
              },
              "test/test-tfmini-esp32-s3-ard.yaml": {
                "external_components.source.re": "${{ github.ref }}"
              }
            }

      - name: ESPHome ${{ matrix.esphome-version }}
        if: steps.esphome-release.outputs.tag != steps.test-release.outputs.tag
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}

      - name: Commit and push json changes
        if: success() && steps.esphome-release.outputs.tag != steps.test-release.outputs.tag
        uses: devops-infra/action-commit-push@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update last successfully tested ESPHome release version to ${{steps.test-release.outputs.tag}}"

