name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "Only one at a time"
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #### Modify below here to match your project ####
        file:
          - test/test-stusb4500-esp32-s3-idf
          - test/test-stusb4500-esp32-s3-ard
          - test/test-tfmini-esp32-s3-idf
          - test/test-tfmini-esp32-s3-ard
        #### Modify above here to match your project ####
        esphome-version:
          - stable
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Get latest ESPHome release tag
        id: esphome-release             # The step ID to refer to later
        uses: oprypin/find-latest-tag@v1
        with:
          repository: esphome/esphome   # The repository to scan
          releases-only: true           # We know that all relevant tags have a GitHub release for them

      - name: Get last tested ESPHome release tag
        id: test-release
        run: |
          tag=$(jq -r '.last_tested_tag' test/.test-data.json)

      - name: Should we test? Commit?
        id: test-conditions
        run: |
          run_test=1
          commit=0
          if ["${{ github.event_name }}" == "schedule"]; then
            echo "This is a scheduled CI"
            echo "Latest ESPHome Release ${{ steps.esphome-release.outputs.tag }}." >>  $GITHUB_OUTPUT
            echo "Last tested ESPHome Release ${{ steps.test-release.outputs.tag }}." >>  $GITHUB_OUTPUT
            if ["${{ steps.esphome-release.outputs.tag }}" == "${{ steps.test-release.outputs.tag }}"]; then
              run_test=0
              echo "No change in version. There is no reason to test again."
            else
              echo "We should test again."
              commit=1
            fi
          else
            echo "This is a commit, always run tests."
          fi
          
      - name: Update reference
        if: steps.esphome-release.outputs.tag != steps.test-release.outputs.tag
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          commitChange: false
          message: "Update reference"
          branch: ${{ github.ref }}
          changes: |
            {
              "test/test-stusb4500-esp32-s3-idf.yaml": {
                "external_components.source.ref": "${{ github.ref }}"
              },
              "test/test-tfmini-esp32-s3-idf.yaml": {
                "external_components.source.ref": "${{ github.ref }}"
              },
              "test/test-stusb4500-esp32-s3-ard.yaml": {
                "external_components.source.ref": "${{ github.ref }}"
              },
              "test/test-tfmini-esp32-s3-ard.yaml": {
                "external_components.source.ref": "${{ github.ref }}"
              }
            }

      - name: ESPHome ${{ matrix.esphome-version }}
        if: steps.test-conditions.outputs.run_test != 0
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}

  # commit:
  #   name: Commit if scheduled check
  #   needs: [ci]
  #   runs-on: ubuntu-latest
  #   # - name: Commit and push json changes
  #   #   if: success() && steps.test-conditions.outputs.commit != 0
  #   #   uses: devops-infra/action-commit-push@v1.0.3
  #   #   with:
  #   #     github_token: ${{ secrets.GITHUB_TOKEN }}
  #   #     commit_message: "Update last successfully tested ESPHome release version to ${{steps.test-release.outputs.tag}}"

